In [1]:
import numpy as np

In [9]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
dataTwo = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]

# 행렬과 스칼라의 곱
for i in range(len(data)):
    for j in range(len(data[0])):
        data[i][j] *= 2

print(data)
        
# 행렬끼리 덧셈
for i in range(len(data)):
    for j in range(len(data[0])):
        data[i][j] += dataTwo[i][j]

print(data)

[[2, 4, 6], [8, 10, 12], [14, 16, 18]]
[[3, 5, 7], [10, 12, 14], [17, 19, 21]]


In [2]:
import numpy as np

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
dataTwo = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]

a = np.array(data)
b = np.array(dataTwo)

a
a * 2
a + a
a + b
a * b # 행렬의 곱 아니고, 원소 끼리의 곱임
np.dot(a, b)
# [[1, 2, 3], 
#  [4, 5, 6], 
#  [7, 8, 9]]

# [[1, 1, 1], 
#  [2, 2, 2], 
#  [3, 3, 3]]

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

### 행렬의 곱(연습문제)

```
 [[2, 3],  X  [[7, 8],   =   [[23, 28],
  [5, 1]]      [3, 4]]        [38, 44]]
```

In [5]:
arrOne = np.array([[2, 3], [5, 1]])
arrTwo = np.array([[7, 8], [3, 4]])

np.dot(arrOne, arrTwo)

array([[23, 28],
       [38, 44]])

* [단위행렬](https://ko.wikipedia.org/wiki/%EB%8B%A8%EC%9C%84%ED%96%89%EB%A0%AC)
* [역행렬](https://ko.wikipedia.org/wiki/%EA%B0%80%EC%97%AD%ED%96%89%EB%A0%AC)

## python

* int,float, complex, string, bool, list, tuple, dict, set

## numpy

* 단일 값을 메모리에 저장하는데 필요한 bit수를 의미합니다.


1. int(8bit, 16bit, 32bit, 64bit) i1, i2, i4, i8
  - 부호가 있음
  - 비트수 만큼 크기를 가지는 정수형


2. unit(8bit, 16bit, 32bit, 64bit) u1, u2, u4, u8
 - 부호가 없음 
 - 비트수 만큼 크기를 가지는 정수형


3. float(16bit, 32bit, 64bit, 128bit) f2, f4, f8, f16
  - 부호가 있음
  - 비트수 만큼 크기를 가지는 실수형


4. 복소수형
  - complex64 : 두개의 32비트 부동 소수점으로 표시되는 복소수 c8
  - complex128 : 두개의 64비트 부동소수점으로 표시되는 복소수 c16


5. unicode
 - 고정 길이 문자열 unicode


6. bool
 - True, False

In [21]:
data = [1.1, 2, 3]

a = np.array(data)
a.dtype

dtype('float64')

In [22]:
data = [1.1, 2, 3]

a = np.array(data, dtype=np.float32)
a.dtype

dtype('float32')

In [24]:
data = [1.1, 2, 3]

a = np.array(data, dtype=np.int32)
a.dtype
a

array([1, 2, 3])

In [9]:
data = [1.1, 2, 3]

a = np.array(data, dtype='i4')
a
a.dtype

dtype('int32')

In [28]:
data = [1.1, 2, 3]

a = np.float64(data)
a.dtype
a
a = np.int32(a)
a

array([1, 2, 3])

In [30]:
data = [1.1, 2, 3]

a = np.float64(data)
a.dtype
a = a.astype(np.int64)
a

array([1, 2, 3], dtype=int64)

In [31]:
data = [1.1, 2, 3]

a = np.float64(data)
a.dtype
a = a.astype(np.string_)
a

array([b'1.1', b'2.0', b'3.0'], dtype='|S32')

In [43]:
a = np.uint16(0)
a.dtype
a = a - 1
a.dtype

dtype('int32')

In [44]:
a = np.uint16(-1)
a

65535

In [6]:
2**8

256

In [7]:
2**16 ## 일반 int16의 최댓값은? 65536 / 2 - 1

65536

## 차원

In [53]:
# 0 차원
a = np.array(1)
a
print(a.shape, a.ndim)

0

In [54]:
# 1 차원
a = np.array([1, 2, 3])
a
print(a.shape, a.ndim)

(3,) 1


In [55]:
# 1 차원
a = np.array([1])
a
print(a.shape, a.ndim)

(1,) 1


In [56]:
# 2 차원
a = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
a
print(a.shape, a.ndim)

(3, 3) 2


In [57]:
# 2 차원
a = np.array([[1]])
a
print(a.shape, a.ndim)

(1, 1) 2


In [59]:
# 3 차원(3차원 이상의 다차원의 행렬을 Tensor)
a = np.array([[[1, 2], [1, 2], [1, 2]], [[1, 2], [1, 2], [1, 2]]])
a
print(a.shape, a.ndim)

(2, 3, 2) 3


## arange와 reshape_값의 호출(indexing, slicing)

In [61]:
a = np.array([i for i in range(2, 11, 2)])
a

array([ 2,  4,  6,  8, 10])

In [62]:
a = np.array(range(2, 11, 2))
a

array([ 2,  4,  6,  8, 10])

In [13]:
np.arange(10)
np.arange(2, 11, 2)
np.arange(10, 15, .5)
np.arange(10, 2, -1)
np.arange(10, 2, -1.5)
# np.linspace(0, 10, 20)   # 이것도 많이 사용합니다.
# np.linspace(0, 10, 21)   # 이것도 많이 사용합니다.

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [68]:
a = np.arange(10)
a.ndim
a.shape
a.size

10

In [16]:
a = np.arange(40).reshape(2, 5, 4)
b = np.arange(40).reshape(1, 1, 2, 5, 4) # 형태는 같지만 5차원입니다.
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]]])

In [76]:
a[0][1][1]

5

In [80]:
a[-1][-3][-3]

29

In [81]:
a[1][2][1]

29

In [82]:
a[-1, -3, -3]

29

In [83]:
a[1, 2, 1]

29

In [84]:
a[a > 30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

In [29]:
## Boolean Indexing 맛보기
a > 30
(a>30)&(a%2==0)
a[(a>30)&(a%2==0)]

array([32, 34, 36, 38])

## slicing

In [85]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [86]:
a[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [87]:
a[5:20:2] #a[start:stop:step]

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [89]:
a = a.reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [32]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
a[:, 1]
a[1, :] #a[1]

array([ 6,  7,  8,  9, 10, 11])

In [93]:
a[:3, :3]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

### 연습문제
```
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])  
에서 
[[8,   9, 10],
 [14, 15, 16],
 [20, 21, 22]]
 
의 총 합을 구해주세요.
```

In [45]:
a[1:4, 2:]
sum(a[1:4, 2:]) #np.sum(a[1:4, 2:], axis=0)
sum(sum(a[1:4, 2:]))
np.sum(a[1:4, 2:])

s = 0
for i in a[1:4, 2:]:
    for j in i:
        s += j
        
s

186

In [94]:
a[::2, ::2]

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

In [98]:
b = a[::2, ::2]
b

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

In [99]:
b[0] = 100
b

array([[100, 100, 100],
       [ 12,  14,  16],
       [ 24,  26,  28]])

In [50]:
test = np.arange(10)
testTwo = test[:5]
testTwo
testTwo[0] = 1000
test

###

test = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
testTwo = test[:5]
testTwo
testTwo[0] = 1000
test

###

test = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
testTwo = test
testTwo
testTwo[0] = 1000
test

[1000, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [101]:
b = a[::2, ::2].copy()
b

array([[100, 100, 100],
       [ 12,  14,  16],
       [ 24,  26,  28]])

In [102]:
b[0] = 1000
b

array([[1000, 1000, 1000],
       [  12,   14,   16],
       [  24,   26,   28]])

In [103]:
a

array([[100,   1, 100,   3, 100,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29]])

In [104]:
a = np.arange(30).reshape(2, 5, 3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [105]:
a[:,:,1]

array([[ 1,  4,  7, 10, 13],
       [16, 19, 22, 25, 28]])

In [106]:
a[:,1,:]

array([[ 3,  4,  5],
       [18, 19, 20]])

In [107]:
a[1,:,:]

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [108]:
a[1,:,::-1]

array([[17, 16, 15],
       [20, 19, 18],
       [23, 22, 21],
       [26, 25, 24],
       [29, 28, 27]])

## 배열의 연결과 분할

In [115]:
x = [1, 2, 3]
y = [4, 5, 6]

# np.array(x) + np.array(y)
a = np.array(x)
b = np.array(y)

np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6])

In [116]:
a = np.arange(10).reshape(2, 5)
b = np.arange(10, 20).reshape(2, 5)

np.concatenate([a, b])

# a = [[ 0,  1,  2,  3,  4],
#      [ 5,  6,  7,  8,  9]],
# b = [[10, 11, 12, 13, 14],
#      [15, 16, 17, 18, 19]]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
a = np.arange(10).reshape(2, 5)
b = np.arange(10, 20).reshape(2, 5)

np.concatenate([[a, b]])

# a = [[ 0,  1,  2,  3,  4],
#      [ 5,  6,  7,  8,  9]],
# b = [[10, 11, 12, 13, 14],
#      [15, 16, 17, 18, 19]]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [118]:
a = np.arange(10).reshape(2, 5)
b = np.arange(10, 20).reshape(2, 5)

# np.concatenate([a, b, a, b])
np.concatenate([[a, b], [a, b]])
# a = [[ 0,  1,  2,  3,  4],
#      [ 5,  6,  7,  8,  9]],
# b = [[10, 11, 12, 13, 14],
#      [15, 16, 17, 18, 19]]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [55]:
np.concatenate([a, b], axis=0)
np.concatenate([a, b], axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [126]:
a = np.arange(12).reshape(2, 6)
b = np.arange(10, 20).reshape(2, 5)

# np.vstack([a, b]) #vertical stack
np.hstack([a, b]) #horizontal stack

array([[ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 15, 16, 17, 18, 19]])

In [130]:
a = np.arange(15).reshape(3, 5)
b = np.arange(10, 20).reshape(2, 5)

np.vstack([a, b]) #vertical stack

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [137]:
a = np.arange(12)
# np.split(a, 5)
# np.split(a, 2)
np.split(a, 3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [141]:
a = np.arange(10, 121, 10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [142]:
np.split(a, [3, 5, 9, 10])

[array([10, 20, 30]),
 array([40, 50]),
 array([60, 70, 80, 90]),
 array([100]),
 array([110, 120])]

In [153]:
a = np.arange(10, 121, 10).reshape(3, 4)
a

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [161]:
# np.vsplit(a, 3)
np.hsplit(a, 4)[0]

array([[10],
       [50],
       [90]])

## 다양한 Matrix 만들기

In [162]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [164]:
b = np.ones(12)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [165]:
c = np.ones([3, 4])
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [166]:
c = np.ones([3, 4, 5])
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [167]:
c = np.zeros([3, 4, 5])
c

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [56]:
d = np.eye(4)
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [63]:
# np.eye(3, 3, 3, 3) #다차원은 Error

In [172]:
e = np.arange(9).reshape(3, 3)
e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [173]:
np.dot(d, e)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [174]:
np.empty(10)

array([8.90070286e-308, 2.11393900e-307, 1.27945906e-307, 1.11258192e-307,
       9.79098366e-307, 1.00133162e-307, 1.11261027e-306, 1.29061821e-306,
       8.90103559e-307, 1.24611470e-306])

In [178]:
np.full((3, 4), 100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [180]:
np.linspace(2, 10, 6)

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

In [181]:
np.linspace(2, 100, 10)

array([  2.        ,  12.88888889,  23.77777778,  34.66666667,
        45.55555556,  56.44444444,  67.33333333,  78.22222222,
        89.11111111, 100.        ])

In [182]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [183]:
a.ravel() #펼침

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [184]:
a.ravel(order='C')#행기준

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [185]:
a.ravel(order='F')#열기준

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

## 유니버셜 함수

In [199]:
max(range(100))

99

In [200]:
min(range(100))

0

In [201]:
%%timeit

for i in range(10):
    max(range(1000000))

425 ms ± 23.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [202]:
%%timeit

for i in range(10):
    np.max(np.arange(1000000))

43.8 ms ± 2.52 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
# np.max()
# np.min()

In [2]:
import numpy as np

a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
# np.max(a)
# max([[1, 2, 3], [4, 1, 1], [1, 8, 9], [8, 2, 3]])
# np.max([[1, 2, 3], [4, 1, 1], [1, 8, 9], [8, 2, 3]])
np.max([[1, 2, 3], [4, 1, 1], [1, 8, 9], [8, 2, 3]], axis=1)

array([3, 4, 9, 8])

In [8]:
np.max(a, axis=0)

array([ 8,  9, 10, 11])

In [222]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [223]:
a[0][3] = 1
np.max(a, axis=1)

array([ 2,  7, 11])

### Axis 2번째 튜토리얼

```
[[11, 13, 22],
 [ 6,  3, 33],
 [47,  9,  3],
 [ 1, 10, 11]]
```

In [25]:
test = [[11, 13, 22],
        [ 6,  3, 33],
        [47,  9,  3],
        [ 1, 10, 11]]

In [27]:
np.max(test)
np.min(test)
np.sum(test)

169

In [34]:
np.max(test, axis=0)
np.min(test, axis=0)
np.sum(test, axis=0)

array([65, 35, 69])

In [35]:
np.max(test, axis=1)
np.min(test, axis=1)
np.sum(test, axis=1)

array([46, 42, 59, 22])

In [64]:
a = np.arange(30).reshape(2, 5, 3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [73]:
np.max(a)
# max(a) : error
# max(a.flatten())
# max(a.ravel())

29

In [66]:
np.max(a, axis=0) #(2, 5, 3)중 처음 값을 기준으로 최댓값 -> 반환형 : (5, 3)

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [67]:
np.max(a, axis=1) #(2, 5, 3)중 중간 값을 기준으로 최댓값 -> 반환형 : (2, 3)

array([[12, 13, 14],
       [27, 28, 29]])

In [68]:
np.max(a, axis=2) #(2, 5, 3)중 마지막 값을 기준으로 최댓값 -> 반환형 : (2, 5)

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29]])

## 집계 함수

In [224]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [227]:
a[0][0] = 100
np.mean(a) #평균

13.833333333333334

In [228]:
np.median(a) #중앙값

6.5

* [표준편차](https://ko.wikipedia.org/wiki/%ED%91%9C%EC%A4%80_%ED%8E%B8%EC%B0%A8)
* [분산](https://ko.wikipedia.org/wiki/%EB%B6%84%EC%82%B0)
---
* [유튜브 영상 추천](https://youtu.be/trFS6ug4_T4)
* [칸아카데미 영상 추천](https://ko.khanacademy.org/math/statistics-probability/analysis-of-variance-anova-library)

In [232]:
np.std(a) #표준편차

26.15604880116431

In [233]:
np.var(a) #분산

684.138888888889

In [234]:
np.sum(a) #합

166

In [235]:
np.sum(a, axis=1) #합

array([106,  22,  38])

In [236]:
a

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [238]:
np.cumsum(a) #누적값

array([100, 101, 103, 106, 110, 115, 121, 128, 136, 145, 155, 166],
      dtype=int32)

In [239]:
np.min(a)

1

In [240]:
np.argmin(a) #위치(index)

1

In [241]:
np.argmax(a) #위치

0

In [243]:
np.any(a) # True인 것이 하나라도 있는가?

True

In [244]:
np.all(a) # 모두가 True인가?

True

In [85]:
np.nansum(a)
np.nansum([1, 2, 3, 4, 0, 0, np.nan, np.nan]) #숫자가 아닌 것까지 모두 더함
np.sum([1, 2, 3, 4, 0, 0, np.nan, np.nan]) #더하는 숫자가 nan이면 nan 반환
# np.isnan(np.array([1, 2, 3, 4, 0, 0, np.nan, np.nan]))
np.isnan(np.array([1, 2, 3, 4, 0, 0, np.nan, np.nan])).sum() # 결측치만 모두 더함

2

In [246]:
a

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [247]:
a > 5

array([[ True, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [248]:
np.all(a > 5)

False

In [249]:
np.all(a > -5)

True

In [250]:
np.where(a > 5) #where의 반환값은 기본적으로 index

(array([0, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([0, 2, 3, 0, 1, 2, 3], dtype=int64))

In [251]:
a

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [253]:
np.where(a > 5, a, -100)

array([[ 100, -100, -100, -100],
       [-100, -100,    6,    7],
       [   8,    9,   10,   11]])

In [259]:
a = np.arange(36).reshape(3, 4, 3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [262]:
np.sum(a)
np.sum(a, axis=1)
np.sum(a, axis=2)

array([[  3,  12,  21,  30],
       [ 39,  48,  57,  66],
       [ 75,  84,  93, 102]])

## Boolean Indexing

In [264]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [265]:
a > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [266]:
a[a > 5]

array([ 6,  7,  8,  9, 10, 11])

In [267]:
a[a > 5] = 1
a

array([[0, 1, 2, 3],
       [4, 5, 1, 1],
       [1, 1, 1, 1]])

In [274]:
a[~(a == 1)]

array([0, 2, 3, 4, 5])

In [275]:
a[~(a == 1) & (a < 4)]

array([0, 2, 3])

In [276]:
a[~(a == 1) | (a < 4)]

array([0, 1, 2, 3, 4, 5, 1, 1, 1, 1, 1, 1])

## Broadcast

In [277]:
np.array([1, 2, 3]) + 1

array([2, 3, 4])

In [281]:
np.arange(9).reshape(3, 3) + np.array([1, 2, 3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [284]:
np.arange(27).reshape(3, 3, 3) + np.array([1, 2, 3])

array([[[ 1,  3,  5],
        [ 4,  6,  8],
        [ 7,  9, 11]],

       [[10, 12, 14],
        [13, 15, 17],
        [16, 18, 20]],

       [[19, 21, 23],
        [22, 24, 26],
        [25, 27, 29]]])

## random

In [294]:
import random as r

r.randint(1, 10) # 1부터 10까지의 임의의 정수를 리턴
r.random() # 0부터 1까지의 부동소수점 숫자를 리턴
r.uniform(1, 10) # 1부터 10까지의 부동소수점 숫자를 리턴
r.randrange(1, 10, 2)

7

In [297]:
l = [i for i in range(20)]
r.shuffle(l)
l

[3, 9, 4, 19, 17, 11, 0, 14, 5, 7, 12, 15, 13, 8, 1, 10, 2, 6, 18, 16]

In [302]:
r.choice(l)

17

In [306]:
r.sample(l, 5)

[9, 15, 12, 17, 19]

In [315]:
r.seed(7)
r.randint(1, 10)

6

In [322]:
np.random.randint(1, 10)
np.random.normal(1, 10, size=(10))
np.random.uniform(1, 10, size=(3, 4))

array([-17.25059395, -11.312764  ,   7.60166855,  -4.95988454,
       -10.23834312, -14.29432166,   1.67048294,  -4.34169123,
         0.78400994,   4.74873551])

In [324]:
np.random.seed(1)
np.random.randint(1, 10)

6