In [1]:
import numpy as np

In [9]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
dataTwo = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]

# 행렬과 스칼라의 곱
for i in range(len(data)):
    for j in range(len(data[0])):
        data[i][j] *= 2

print(data)
        
# 행렬끼리 덧셈
for i in range(len(data)):
    for j in range(len(data[0])):
        data[i][j] += dataTwo[i][j]

print(data)

[[2, 4, 6], [8, 10, 12], [14, 16, 18]]
[[3, 5, 7], [10, 12, 14], [17, 19, 21]]


In [2]:
import numpy as np

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
dataTwo = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]

a = np.array(data)
b = np.array(dataTwo)

a
a * 2
a + a
a + b
a * b # 행렬의 곱 아니고, 원소 끼리의 곱임
np.dot(a, b)
# [[1, 2, 3], 
#  [4, 5, 6], 
#  [7, 8, 9]]

# [[1, 1, 1], 
#  [2, 2, 2], 
#  [3, 3, 3]]

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [5]:
arrOne = np.array([[2, 3], [5, 1]])
arrTwo = np.array([[7, 8], [3, 4]])

np.dot(arrOne, arrTwo)

array([[23, 28],
       [38, 44]])

In [21]:
data = [1.1, 2, 3]

a = np.array(data)
a.dtype

dtype('float64')

In [22]:
data = [1.1, 2, 3]

a = np.array(data, dtype=np.float32)
a.dtype

dtype('float32')

In [24]:
data = [1.1, 2, 3]

a = np.array(data, dtype=np.int32)
a.dtype
a

array([1, 2, 3])

In [9]:
data = [1.1, 2, 3]

a = np.array(data, dtype='i4')
a
a.dtype

dtype('int32')

In [28]:
data = [1.1, 2, 3]

a = np.float64(data)
a.dtype
a
a = np.int32(a)
a

array([1, 2, 3])

In [30]:
data = [1.1, 2, 3]

a = np.float64(data)
a.dtype
a = a.astype(np.int64)
a

array([1, 2, 3], dtype=int64)

In [31]:
data = [1.1, 2, 3]

a = np.float64(data)
a.dtype
a = a.astype(np.string_)
a

array([b'1.1', b'2.0', b'3.0'], dtype='|S32')

In [43]:
a = np.uint16(0)
a.dtype
a = a - 1
a.dtype

dtype('int32')

In [44]:
a = np.uint16(-1)
a

65535

In [6]:
2**8

256

In [7]:
2**16 ## 일반 int16의 최댓값은? 65536 / 2 - 1

65536

## 차원

In [53]:
# 0 차원
a = np.array(1)
a
print(a.shape, a.ndim)

0

In [54]:
# 1 차원
a = np.array([1, 2, 3])
a
print(a.shape, a.ndim)

(3,) 1


In [55]:
# 1 차원
a = np.array([1])
a
print(a.shape, a.ndim)

(1,) 1


In [56]:
# 2 차원
a = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
a
print(a.shape, a.ndim)

(3, 3) 2


In [57]:
# 2 차원
a = np.array([[1]])
a
print(a.shape, a.ndim)

(1, 1) 2


In [59]:
# 3 차원(3차원 이상의 다차원의 행렬을 Tensor)
a = np.array([[[1, 2], [1, 2], [1, 2]], [[1, 2], [1, 2], [1, 2]]])
a
print(a.shape, a.ndim)

(2, 3, 2) 3


## arange와 reshape_값의 호출(indexing, slicing)

In [61]:
a = np.array([i for i in range(2, 11, 2)])
a

array([ 2,  4,  6,  8, 10])

In [62]:
a = np.array(range(2, 11, 2))
a

array([ 2,  4,  6,  8, 10])

In [13]:
np.arange(10)
np.arange(2, 11, 2)
np.arange(10, 15, .5)
np.arange(10, 2, -1)
np.arange(10, 2, -1.5)
# np.linspace(0, 10, 20)   # 이것도 많이 사용합니다.
# np.linspace(0, 10, 21)   # 이것도 많이 사용합니다.

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [68]:
a = np.arange(10)
a.ndim
a.shape
a.size

10

In [16]:
a = np.arange(40).reshape(2, 5, 4)
b = np.arange(40).reshape(1, 1, 2, 5, 4) # 형태는 같지만 5차원입니다.
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]]])

In [76]:
a[0][1][1]

5

In [80]:
a[-1][-3][-3]

29

In [81]:
a[1][2][1]

29

In [82]:
a[-1, -3, -3]

29

In [83]:
a[1, 2, 1]

29

In [84]:
a[a > 30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

In [29]:
## Boolean Indexing 맛보기
a > 30
(a>30)&(a%2==0)
a[(a>30)&(a%2==0)]

array([32, 34, 36, 38])

## slicing

In [85]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [86]:
a[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [87]:
a[5:20:2] #a[start:stop:step]

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [89]:
a = a.reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [32]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
a[:, 1]
a[1, :] #a[1]

array([ 6,  7,  8,  9, 10, 11])

In [93]:
a[:3, :3]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

### 연습문제
```
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])  
에서 
[[8,   9, 10],
 [14, 15, 16],
 [20, 21, 22]]
 
의 총 합을 구해주세요.
```

In [45]:
a[1:4, 2:]
sum(a[1:4, 2:]) #np.sum(a[1:4, 2:], axis=0)
sum(sum(a[1:4, 2:]))
np.sum(a[1:4, 2:])

s = 0
for i in a[1:4, 2:]:
    for j in i:
        s += j
        
s

186

In [94]:
a[::2, ::2]

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

In [98]:
b = a[::2, ::2]
b

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

In [99]:
b[0] = 100
b

array([[100, 100, 100],
       [ 12,  14,  16],
       [ 24,  26,  28]])

In [50]:
test = np.arange(10)
testTwo = test[:5]
testTwo
testTwo[0] = 1000
test

###

test = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
testTwo = test[:5]
testTwo
testTwo[0] = 1000
test

###

test = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
testTwo = test
testTwo
testTwo[0] = 1000
test

[1000, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [101]:
b = a[::2, ::2].copy()
b

array([[100, 100, 100],
       [ 12,  14,  16],
       [ 24,  26,  28]])

In [102]:
b[0] = 1000
b

array([[1000, 1000, 1000],
       [  12,   14,   16],
       [  24,   26,   28]])

In [103]:
a

array([[100,   1, 100,   3, 100,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29]])

In [104]:
a = np.arange(30).reshape(2, 5, 3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [105]:
a[:,:,1]

array([[ 1,  4,  7, 10, 13],
       [16, 19, 22, 25, 28]])

In [106]:
a[:,1,:]

array([[ 3,  4,  5],
       [18, 19, 20]])

In [107]:
a[1,:,:]

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [108]:
a[1,:,::-1]

array([[17, 16, 15],
       [20, 19, 18],
       [23, 22, 21],
       [26, 25, 24],
       [29, 28, 27]])

## 배열의 연결과 분할

In [115]:
x = [1, 2, 3]
y = [4, 5, 6]

# np.array(x) + np.array(y)
a = np.array(x)
b = np.array(y)

np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6])

In [116]:
a = np.arange(10).reshape(2, 5)
b = np.arange(10, 20).reshape(2, 5)

np.concatenate([a, b])

# a = [[ 0,  1,  2,  3,  4],
#      [ 5,  6,  7,  8,  9]],
# b = [[10, 11, 12, 13, 14],
#      [15, 16, 17, 18, 19]]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
a = np.arange(10).reshape(2, 5)
b = np.arange(10, 20).reshape(2, 5)

np.concatenate([[a, b]])

# a = [[ 0,  1,  2,  3,  4],
#      [ 5,  6,  7,  8,  9]],
# b = [[10, 11, 12, 13, 14],
#      [15, 16, 17, 18, 19]]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [118]:
a = np.arange(10).reshape(2, 5)
b = np.arange(10, 20).reshape(2, 5)

# np.concatenate([a, b, a, b])
np.concatenate([[a, b], [a, b]])
# a = [[ 0,  1,  2,  3,  4],
#      [ 5,  6,  7,  8,  9]],
# b = [[10, 11, 12, 13, 14],
#      [15, 16, 17, 18, 19]]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [55]:
np.concatenate([a, b], axis=0)
np.concatenate([a, b], axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [126]:
a = np.arange(12).reshape(2, 6)
b = np.arange(10, 20).reshape(2, 5)

# np.vstack([a, b]) #vertical stack
np.hstack([a, b]) #horizontal stack

array([[ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 15, 16, 17, 18, 19]])

In [130]:
a = np.arange(15).reshape(3, 5)
b = np.arange(10, 20).reshape(2, 5)

np.vstack([a, b]) #vertical stack

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [137]:
a = np.arange(12)
# np.split(a, 5)
# np.split(a, 2)
np.split(a, 3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [141]:
a = np.arange(10, 121, 10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [142]:
np.split(a, [3, 5, 9, 10])

[array([10, 20, 30]),
 array([40, 50]),
 array([60, 70, 80, 90]),
 array([100]),
 array([110, 120])]

In [153]:
a = np.arange(10, 121, 10).reshape(3, 4)
a

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [161]:
# np.vsplit(a, 3)
np.hsplit(a, 4)[0]

array([[10],
       [50],
       [90]])